import {
  black,
  blue,
  dark_blue,
  dark_grey,
  end_base_button_colour,
  end_base_button_colour_opaque,
  green,
  grey,
  red,
  selection_colour_opaque,
  start_base_button_colour,
  start_base_button_colour_opaque,
  true_black,
  white,
} from "./colors";

export const generateDarkTheme = {
  // ...DefaultTheme,
  colors: {
    // ...DefaultTheme.colors,
    primary: start_base_button_colour,
    accent: end_base_button_colour,
  },
  theme: {
    backgroundColor: "rgba(32,32,33,1)",
    slider_dark: start_base_button_colour,
    slider_light: end_base_button_colour,
    link_color: "whitesmoke",
    link_color_hovered: "#858FEE",
    font_color: "white",
    base_button_color: "#EC690B",
    yellow: "#ffca0094",
    black: black,
    red: red,
    green: green,
    blue: blue,
    grey: grey,
    lightGrey: "rgba(226, 226, 226, 1)",
    mediumGrey: "rgba(43, 43, 43, 1)",
    darkGrey: dark_grey,
    semi_transparent: "rgba(255, 255, 255, 0.5)",
    white: white,
    true_black: true_black,
    contrast_font_color: white,
    selection_color: start_base_button_colour,
    selection_colour_opaque: selection_colour_opaque,
    start_base_button_colour: start_base_button_colour,
    start_base_button_colour_opaque: start_base_button_colour_opaque,
    end_base_button_colour_opaque: end_base_button_colour_opaque,
    end_base_button_colour: end_base_button_colour,
    inputBackgroundColor: true_black,
    inputPlaceholderColor: grey,
    pickerMenuColor: grey,
    selectedTabColor: dark_blue,
    baseScreenBackgroundColor: dark_grey,
    base_button_font_color: white,
    start_skeleton_color: grey,
    end_skeleton_color: start_base_button_colour,
    highlight_selection_color: "#A828D4",
    backgroundContrastColor: "rgba(59, 59, 59, 1)",
    backgroundHighContrastColor: "rgba(255,255,255,0.8)",
    border_color: "rgba(246,246,246,.25)",
    border_color_highlighted: "rgba(200,112,255,.50)",
    box_shadow: `0 0px 0px ${grey}`,
    skeleton_color: "#202020",
    skeleton_highlight_color: "#444",
    border: "1px solid rgba(246,246,246,.25)",
    disabled_color: grey,
    backgroundPopupColor: "rgba(32,32,33,0.99)",
    custom_component_border: "0px solid transparent",
    avatar_background_color: end_base_button_colour,
    avatar_foreground_color: white,
    editor_background_color: true_black,
    editor_foreground_color: white,
    orangeBtnColor: "#E95E0B",
    small_font_size: 16,
    base_font_size: 18,
    medium_font_size: 20,
    large_font_size: 24,
    largest_font_size: 26,
    font_bold: "bold",
    font_normal: "normal",
  },
};

export const generateLightTheme = {
  // ...DefaultTheme,
  colors: {
    // ...DefaultTheme.colors,
    primary: start_base_button_colour,
    accent: end_base_button_colour,
  },
  theme: {
    backgroundColor: "#ffffff",
    slider_dark: "#5e5e5e",
    slider_light: "#bdc3c7",
    link_color: "var(--dark-blue)",
    link_color_hovered: "purple",
    font_color: "black",
    base_button_color: "#EC690B",
    yellow: "#ffca0094",
    red: red,
    green: "var(--green)",
    blue: "#016bfc",
    grey: grey,
    black: black,
    lightGrey: "rgba(239, 239, 239, 1)",
    mediumGrey: "rgba(215, 215, 215, 1)",
    darkGrey: dark_grey,
    semi_transparent: "rgba(0, 0, 0, 0.5)",
    white: white,
    true_black: true_black,
    selection_color: start_base_button_colour,
    base_button_font_color: white,
    start_skeleton_color: grey,
    end_skeleton_color: start_base_button_colour,
    contrast_font_color: white,
    selection_colour_opaque: selection_colour_opaque,
    start_base_button_colour: start_base_button_colour,
    end_base_button_colour: end_base_button_colour,
    avatar_background_color: end_base_button_colour,
    avatar_foreground_color: white,
    editor_background_color: white,
    editor_foreground_color: true_black,
    start_base_button_colour_opaque: start_base_button_colour_opaque,
    end_base_button_colour_opaque: end_base_button_colour_opaque,
    inputBackgroundColor: "rgba(245, 245, 245, 1)",
    inputPlaceholderColor: dark_grey,
    selectedTabColor: dark_blue,
    baseScreenBackgroundColor: white,
    pickerMenuColor: grey,
    highlight_selection_color: "#A828D4",
    backgroundContrastColor: "#f6f6ff",
    backgroundHighContrastColor: "#e8e8e8",
    border_color: "rgba(195,195,195,.25)",
    border_color_highlighted: "rgba(99,93,255,.50)",
    box_shadow: "0 1px 1px var(--light-grey)",
    border: "1px solid rgba(195,195,195,.25)",
    disabled_color: "var(--medium-grey)",
    backgroundPopupColor: "#f6f6ff",
    custom_component_border: "1px solid rgba(195,195,195,.25)",
    orangeBtnColor: "#E95E0B",
    small_font_size: 16,
    base_font_size: 18,
    medium_font_size: 20,
    large_font_size: 24,
    largest_font_size: 26,
    font_bold: "bold",
    font_normal: "normal",
  },
};

// import { black, blue, green, grey, red, white } from "./colors";

// const generateLightTheme = {
//   theme: {
//     backgroundColor: "#ffffff",
//     link_color: "var(--dark-blue)",
//     link_color_hovered: "purple",
//     font_color: "#5d94d6",
//     base_button_color: "#EC690B",
//     yellow: "#ffca0094",
//     red: "var(--red)",
//     green: "var(--green)",
//     blue: "#016bfc",
//     grey: "var(--medium-grey)",
//     white: "var(--white)",
//     text: black,
//     selection_color: "var(--selection-colour)",
//     highlight_selection_color: "#A828D4",
//     backgroundContrastColor: "#f6f6ff",
//     backgroundHighContrastColor: "#e8e8e8",
//     border_color: "rgba(195,195,195,.25)",
//     border_color_highlighted: "rgba(99,93,255,.50)",
//     box_shadow: "0 1px 1px var(--light-grey)",
//     border: "1px solid rgba(195,195,195,.25)",
//     disabled_color: "var(--medium-grey)",
//     backgroundPopupColor: "#f6f6ff",
//     custom_component_border: "1px solid rgba(195,195,195,.25)",
//     orangeBtnColor: "#E95E0B",
//     small_font_size: 12,
//     base_font_size: 14,
//     medium_font_size: 16,
//     large_font_size: 18,
//     largest_font_size: 24,
//   },
// };

// export default generateLightTheme;
